### ISSUE TITLE
我们的一位成员将你的代码用于商用

### ISSUE THREAD

**Issue by wizardforcel** [KrisYu/LeetCode-CLRS-Python#1]
我们曾经向你请求过这个项目的授权，并放在 [awesome-algorithm](https://github.com/apachecn/awesome-algorithm) 的 `docs/Leetcode_Solutions/Python` 目录下。但是 @lisanaaa 将其用于商用，并删除了仓库里的副本。由于我们是一个相当松散的开源社区，我们几个负责人无法阻止这件事情，望悉知。

**Comment by 0xkookoo** [comment]
- [事情来龙去脉](https://github.com/Lisanaaa/AlgorithmRecord/blob/master/7%E6%9C%8814%E7%89%87%E5%88%BB%E5%85%AC%E5%91%8A%E4%BA%8B%E4%BB%B6%E6%9D%A5%E9%BE%99%E5%8E%BB%E8%84%89.md)
- 我的[小专栏](https://xiaozhuanlan.com/Lisanaaa)在这里，都是我自己新写的东西，如果有代码滥用我立马删除
- 我很抱歉他们居然闹到这里，在这里跟你说一句抱歉
- 我不是他们的成员，我只负责我自己的项目
- 授权是我请求的，跟他们没有任何关系，来龙去脉里能看到我们的邮件通信

**Comment by wizardforcel** [comment]
@Lisanaaa 如果小专栏都是你自己新写的东西，我们的仓库里是这个仓库的东西，你根本没必要删除，简直是做贼心虚。

**Comment by 0xkookoo** [comment]
@wizardforcel 我又不是因为这个小专栏删除的代码，小专栏的版权仍然是我自己的，不影响。慕课网那边希望说后面不要产生任何版权问题，所以我先把代码删了，如果后面代码真的没用到再放回去（我在声明里面也说了），你先把来龙去脉了解完再来说话呗，我跟你也没什么交集你确定你了解的很详细？

Note: 替换为原始代码这个我当时真的没想到，抱歉。
